<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('technologies', ['as'=> 'technologies.index', 'uses' => 'TechnologyController@index']);
Route::post('technologies', ['as'=> 'technologies.store', 'uses' => 'TechnologyController@store']);
Route::get('technologies/create', ['as'=> 'technologies.create', 'uses' => 'TechnologyController@create']);
Route::put('technologies/{technologies}', ['as'=> 'technologies.update', 'uses' => 'TechnologyController@update']);
Route::patch('technologies/{technologies}', ['as'=> 'technologies.update', 'uses' => 'TechnologyController@update']);
Route::get('technologies/{id}/delete', array('as' => 'technologies.delete', 'uses' => 'TechnologyController@getDelete'));
Route::get('technologies/{id}/confirm-delete', array('as' => 'technologies.confirm-delete', 'uses' => 'TechnologyController@getModalDelete'));
Route::get('technologies/{technologies}', ['as'=> 'technologies.show', 'uses' => 'TechnologyController@show']);
Route::get('technologies/{technologies}/edit', ['as'=> 'technologies.edit', 'uses' => 'TechnologyController@edit']);

});

Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('designations', ['as'=> 'designations.index', 'uses' => 'DesignationController@index']);
Route::post('designations', ['as'=> 'designations.store', 'uses' => 'DesignationController@store']);
Route::get('designations/create', ['as'=> 'designations.create', 'uses' => 'DesignationController@create']);
Route::put('designations/{designations}', ['as'=> 'designations.update', 'uses' => 'DesignationController@update']);
Route::patch('designations/{designations}', ['as'=> 'designations.update', 'uses' => 'DesignationController@update']);
Route::get('designations/{id}/delete', array('as' => 'designations.delete', 'uses' => 'DesignationController@getDelete'));
Route::get('designations/{id}/confirm-delete', array('as' => 'designations.confirm-delete', 'uses' => 'DesignationController@getModalDelete'));
Route::get('designations/{designations}', ['as'=> 'designations.show', 'uses' => 'DesignationController@show']);
Route::get('designations/{designations}/edit', ['as'=> 'designations.edit', 'uses' => 'DesignationController@edit']);

});





Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('educationTypes', ['as'=> 'educationTypes.index', 'uses' => 'EducationTypeController@index']);
Route::post('educationTypes', ['as'=> 'educationTypes.store', 'uses' => 'EducationTypeController@store']);
Route::get('educationTypes/create', ['as'=> 'educationTypes.create', 'uses' => 'EducationTypeController@create']);
Route::put('educationTypes/{educationTypes}', ['as'=> 'educationTypes.update', 'uses' => 'EducationTypeController@update']);
Route::patch('educationTypes/{educationTypes}', ['as'=> 'educationTypes.update', 'uses' => 'EducationTypeController@update']);
Route::get('educationTypes/{id}/delete', array('as' => 'educationTypes.delete', 'uses' => 'EducationTypeController@getDelete'));
Route::get('educationTypes/{id}/confirm-delete', array('as' => 'educationTypes.confirm-delete', 'uses' => 'EducationTypeController@getModalDelete'));
Route::get('educationTypes/{educationTypes}', ['as'=> 'educationTypes.show', 'uses' => 'EducationTypeController@show']);
Route::get('educationTypes/{educationTypes}/edit', ['as'=> 'educationTypes.edit', 'uses' => 'EducationTypeController@edit']);

});
