<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('technologies', ['as'=> 'technologies.index', 'uses' => 'TechnologyController@index']);
Route::post('technologies', ['as'=> 'technologies.store', 'uses' => 'TechnologyController@store']);
Route::get('technologies/create', ['as'=> 'technologies.create', 'uses' => 'TechnologyController@create']);
Route::put('technologies/{technologies}', ['as'=> 'technologies.update', 'uses' => 'TechnologyController@update']);
Route::patch('technologies/{technologies}', ['as'=> 'technologies.update', 'uses' => 'TechnologyController@update']);
Route::get('technologies/{id}/delete', array('as' => 'technologies.delete', 'uses' => 'TechnologyController@getDelete'));
Route::get('technologies/{id}/confirm-delete', array('as' => 'technologies.confirm-delete', 'uses' => 'TechnologyController@getModalDelete'));
Route::get('technologies/{technologies}', ['as'=> 'technologies.show', 'uses' => 'TechnologyController@show']);
Route::get('technologies/{technologies}/edit', ['as'=> 'technologies.edit', 'uses' => 'TechnologyController@edit']);

});

Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('designations', ['as'=> 'designations.index', 'uses' => 'DesignationController@index']);
Route::post('designations', ['as'=> 'designations.store', 'uses' => 'DesignationController@store']);
Route::get('designations/create', ['as'=> 'designations.create', 'uses' => 'DesignationController@create']);
Route::put('designations/{designations}', ['as'=> 'designations.update', 'uses' => 'DesignationController@update']);
Route::patch('designations/{designations}', ['as'=> 'designations.update', 'uses' => 'DesignationController@update']);
Route::get('designations/{id}/delete', array('as' => 'designations.delete', 'uses' => 'DesignationController@getDelete'));
Route::get('designations/{id}/confirm-delete', array('as' => 'designations.confirm-delete', 'uses' => 'DesignationController@getModalDelete'));
Route::get('designations/{designations}', ['as'=> 'designations.show', 'uses' => 'DesignationController@show']);
Route::get('designations/{designations}/edit', ['as'=> 'designations.edit', 'uses' => 'DesignationController@edit']);

});





Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('educationTypes', ['as'=> 'educationTypes.index', 'uses' => 'EducationTypeController@index']);
Route::post('educationTypes', ['as'=> 'educationTypes.store', 'uses' => 'EducationTypeController@store']);
Route::get('educationTypes/create', ['as'=> 'educationTypes.create', 'uses' => 'EducationTypeController@create']);
Route::put('educationTypes/{educationTypes}', ['as'=> 'educationTypes.update', 'uses' => 'EducationTypeController@update']);
Route::patch('educationTypes/{educationTypes}', ['as'=> 'educationTypes.update', 'uses' => 'EducationTypeController@update']);
Route::get('educationTypes/{id}/delete', array('as' => 'educationTypes.delete', 'uses' => 'EducationTypeController@getDelete'));
Route::get('educationTypes/{id}/confirm-delete', array('as' => 'educationTypes.confirm-delete', 'uses' => 'EducationTypeController@getModalDelete'));
Route::get('educationTypes/{educationTypes}', ['as'=> 'educationTypes.show', 'uses' => 'EducationTypeController@show']);
Route::get('educationTypes/{educationTypes}/edit', ['as'=> 'educationTypes.edit', 'uses' => 'EducationTypeController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('employerTypes', ['as'=> 'employerTypes.index', 'uses' => 'EmployerTypeController@index']);
Route::post('employerTypes', ['as'=> 'employerTypes.store', 'uses' => 'EmployerTypeController@store']);
Route::get('employerTypes/create', ['as'=> 'employerTypes.create', 'uses' => 'EmployerTypeController@create']);
Route::put('employerTypes/{employerTypes}', ['as'=> 'employerTypes.update', 'uses' => 'EmployerTypeController@update']);
Route::patch('employerTypes/{employerTypes}', ['as'=> 'employerTypes.update', 'uses' => 'EmployerTypeController@update']);
Route::get('employerTypes/{id}/delete', array('as' => 'employerTypes.delete', 'uses' => 'EmployerTypeController@getDelete'));
Route::get('employerTypes/{id}/confirm-delete', array('as' => 'employerTypes.confirm-delete', 'uses' => 'EmployerTypeController@getModalDelete'));
Route::get('employerTypes/{employerTypes}', ['as'=> 'employerTypes.show', 'uses' => 'EmployerTypeController@show']);
Route::get('employerTypes/{employerTypes}/edit', ['as'=> 'employerTypes.edit', 'uses' => 'EmployerTypeController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('projectCategories', ['as'=> 'projectCategories.index', 'uses' => 'ProjectCategoryController@index']);
Route::post('projectCategories', ['as'=> 'projectCategories.store', 'uses' => 'ProjectCategoryController@store']);
Route::get('projectCategories/create', ['as'=> 'projectCategories.create', 'uses' => 'ProjectCategoryController@create']);
Route::put('projectCategories/{projectCategories}', ['as'=> 'projectCategories.update', 'uses' => 'ProjectCategoryController@update']);
Route::patch('projectCategories/{projectCategories}', ['as'=> 'projectCategories.update', 'uses' => 'ProjectCategoryController@update']);
Route::get('projectCategories/{id}/delete', array('as' => 'projectCategories.delete', 'uses' => 'ProjectCategoryController@getDelete'));
Route::get('projectCategories/{id}/confirm-delete', array('as' => 'projectCategories.confirm-delete', 'uses' => 'ProjectCategoryController@getModalDelete'));
Route::get('projectCategories/{projectCategories}', ['as'=> 'projectCategories.show', 'uses' => 'ProjectCategoryController@show']);
Route::get('projectCategories/{projectCategories}/edit', ['as'=> 'projectCategories.edit', 'uses' => 'ProjectCategoryController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('projectStatuses', ['as'=> 'projectStatuses.index', 'uses' => 'ProjectStatusController@index']);
Route::post('projectStatuses', ['as'=> 'projectStatuses.store', 'uses' => 'ProjectStatusController@store']);
Route::get('projectStatuses/create', ['as'=> 'projectStatuses.create', 'uses' => 'ProjectStatusController@create']);
Route::put('projectStatuses/{projectStatuses}', ['as'=> 'projectStatuses.update', 'uses' => 'ProjectStatusController@update']);
Route::patch('projectStatuses/{projectStatuses}', ['as'=> 'projectStatuses.update', 'uses' => 'ProjectStatusController@update']);
Route::get('projectStatuses/{id}/delete', array('as' => 'projectStatuses.delete', 'uses' => 'ProjectStatusController@getDelete'));
Route::get('projectStatuses/{id}/confirm-delete', array('as' => 'projectStatuses.confirm-delete', 'uses' => 'ProjectStatusController@getModalDelete'));
Route::get('projectStatuses/{projectStatuses}', ['as'=> 'projectStatuses.show', 'uses' => 'ProjectStatusController@show']);
Route::get('projectStatuses/{projectStatuses}/edit', ['as'=> 'projectStatuses.edit', 'uses' => 'ProjectStatusController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('qualifications', ['as'=> 'qualifications.index', 'uses' => 'QualificationController@index']);
Route::post('qualifications', ['as'=> 'qualifications.store', 'uses' => 'QualificationController@store']);
Route::get('qualifications/create', ['as'=> 'qualifications.create', 'uses' => 'QualificationController@create']);
Route::put('qualifications/{qualifications}', ['as'=> 'qualifications.update', 'uses' => 'QualificationController@update']);
Route::patch('qualifications/{qualifications}', ['as'=> 'qualifications.update', 'uses' => 'QualificationController@update']);
Route::get('qualifications/{id}/delete', array('as' => 'qualifications.delete', 'uses' => 'QualificationController@getDelete'));
Route::get('qualifications/{id}/confirm-delete', array('as' => 'qualifications.confirm-delete', 'uses' => 'QualificationController@getModalDelete'));
Route::get('qualifications/{qualifications}', ['as'=> 'qualifications.show', 'uses' => 'QualificationController@show']);
Route::get('qualifications/{qualifications}/edit', ['as'=> 'qualifications.edit', 'uses' => 'QualificationController@edit']);

});
